// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqpzgzoijqhgywnerbnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcHpnem9panFoZ3l3bmVyYm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzU3NjgsImV4cCI6MjA3MTU1MTc2OH0.u7u7R6z-6qdZMhWHCu_wEzO8vdGmnvzYuUTX7ty5rmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});